apiVersion: v1
kind: Service
metadata:
  name: {{ include "inhouse-ai.fullname" . }}-openwebui
  labels:
    {{- include "inhouse-ai.openwebui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openwebui.service.type }}
  ports:
    - port: {{ .Values.openwebui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.openwebui.service.type "NodePort") .Values.openwebui.service.nodePort }}
      nodePort: {{ .Values.openwebui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "inhouse-ai.openwebui.selectorLabels" . | nindent 4 }}
